spring.application.name=hackthon
# ======================
# SERVER
# ======================
server.port=8080

# ======================
# DATABASE POSTGRESQL
# ======================
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_learning_db
spring.datasource.username=postgres
spring.datasource.password=Support@2525

spring.datasource.driver-class-name=org.postgresql.Driver

# ======================
# JPA / HIBERNATE
# ======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ======================
# LOGS
# ======================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ======================
# SPRING AI / EXTERNAL API (si tu utilises IA)
# ======================
groq.api.key=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
# gemini.api.key=YOUR_API_KEY

# ======================
# JACKSON (JSON)
# ======================
spring.jackson.serialization.indent_output=true