spring.application.name=hackthon

# ======================
# SERVER
# ======================
server.port=8080

# ======================
# DATABASE POSTGRESQL
# ======================
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_learning_db
spring.datasource.username=postgres
spring.datasource.password=Support@2525
spring.datasource.driver-class-name=org.postgresql.Driver

# ======================
# JPA / HIBERNATE
# ======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# ======================
# GROQ API
# ======================
groq.api.key=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
groq.api.model=llama-3.1-8b-instant

# ======================
# JACKSON
# ======================
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.serialization.indent-output=true

# ======================
# LOGS
# ======================
logging.level.com.hackthon=INFO
logging.level.org.hibernate.SQL=WARN